version: 2.1

jobs:
  deploy:
    docker:
      - image: arvindr226/alpine-ssh
    steps:
      - run: |
          ssh -oStrictHostKeyChecking=no -v $USER@$DNS "\
            sudo -s << 'EOF' && \
            cd /home/ubuntu/sangam && \
            git init && \
            git remote add origin https://github.com/sangammali/ABCP.git && \
            git pull origin master && \
            EOF"
          # Replace <repository_url> with the actual URL of your Git repository

workflows:
  deploy-to-ec2:
    jobs:
      - deploy
