version: 2.1

jobs:
  build:
    docker:
      - image: ubuntu:22.04

    steps:
      - checkout:
          branch: master

      - run:
          name: Set Working Directory and Pull Latest Changes
          command: |
            WORKING_DIR="/home/ubuntu/ABCP"
            cd $WORKING_DIR
            pwd  
            git pull
