version: 2.1

jobs:
  build:
    docker:
      - image: node:18

    steps:
      - checkout

      # Install dependencies and any other setup steps if needed
      - run:
          name: Install dependencies
          command: npm install

      # Run tests or other build steps
      - run:
          name: Run tests
          command: npm test

      # Deployment steps
      - deploy:
          name: Deploy to production
          command: |
            ssh ubuntu@3.147.69.224 "cd /home/ubuntu/ABCP && git pull origin master"
            ssh ubuntu@3.147.69.224 "pm2 reload"
