version: 2.1

jobs:
  deploy:
    docker:
      - image: arvindr226/alpine-ssh
    steps:
      - run: |
          ssh -oStrictHostKeyChecking=no -v $USER@$DNS "\
            sudo cd /home/ubuntu/sangam && \
            sudo git init && \
            sudo git remote add origin https://github.com/sangammali/ABCP.git && \
            sudo git pull origin master"
          # Replace <repository_url> with the actual URL of your Git repository

workflows:
  deploy-to-ec2:
    jobs:
      - deploy

