version: 2.1

jobs:
  build:
    docker:
      - image: node:14

    steps:
      - checkout

      # Install dependencies and any other setup steps if needed
      - run:
          name: Install dependencies
          command: npm install

      # Run tests or other build steps
      - run:
          name: Run tests
          command: npm test

      # Deployment steps
      - deploy:
          name: Deploy to production
          command: |
            echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            ssh-add ~/.ssh/id_rsa
            ssh -o StrictHostKeyChecking=no ubuntu@3.147.69.224 "cd /path/to/your/app && git pull origin master"
            ssh -o StrictHostKeyChecking=no ubuntu@3.147.69.224 "pm2 reload <your_pm2_process_name>"
