version: 2.1

jobs:
  build:
    docker:
      - image: ubuntu:22.04

    steps:
      - checkout:
          branch: master

      - run:
          name: Install SSH client and SSH into Instance
          command: |
            WORKING_DIR="/home/ubuntu/ABCP"

            # Install SSH client
            apt-get update -y
            apt-get install -y openssh-client

            # Your SSH commands here to pull latest changes
            ssh -o StrictHostKeyChecking=no ubuntu@3.147.69.224 "
              mkdir -p $WORKING_DIR &&
              cd $WORKING_DIR &&
              git pull
            "
