version: 2.1

jobs:
  build:
    docker:
      - image: ubuntu:22.04

    steps:
      - checkout:
          branch: master

      - run:
          name: SSH into Instance and Pull Latest Changes
          command: |
            WORKING_DIR="/home/ubuntu/ABCP"

            # Your SSH commands here to pull latest changes
            ssh -o StrictHostKeyChecking=no ubuntu@3.147.69.224 "
              mkdir -p $WORKING_DIR &&
              cd $WORKING_DIR &&
              git pull
            "
