version: 2.1

jobs:
  deploy:
    docker:
      - image: arvindr226/alpine-ssh
    steps:
      - run: ssh -oStrictHostKeyChecking=no -v $USER@$DNS "sudo mkdir -p /home/ubuntu/sangam"

workflows:
  deploy-to-ec2:
    jobs:
      - deploy
